development:
  cloud_name: dvjh8xuhq
  api_key: '254536774566883'
  api_secret: xhEnqbLIt-v4jPtF5GVv5wHox0g
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dvjh8xuhq
  api_key: '254536774566883'
  api_secret: xhEnqbLIt-v4jPtF5GVv5wHox0g
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dvjh8xuhq
  api_key: '254536774566883'
  api_secret: xhEnqbLIt-v4jPtF5GVv5wHox0g
  enhance_image_tag: true
  static_image_support: false
